name = "MTFun"
uuid = "e91a2d32-40e0-4b98-a669-cbf69939a685"
authors = ["Marcus Webb <marcusdavidwebb@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.11"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
